/**
 * Screen handler: CAR Entry (HSE_TgCrEntry)
 * Menu path: Performance -> Action Tracking -> CAR Entry (from HSE.json)
 * C++: NewCarEntryCategory – VIEW_SOURCE_TXN, ...; NEW on tabs sets next serial (HSEMSCommonCategory getNxtSrl).
 * RQ_HSE_4_4_25_18_22 — NEW defaults (site/dept), save parity hooks, getDevInterface on toolbar.
 */

import { handleCarButton } from '../../../utils/carCustomButtons.js';
import { sendButtonClickToBackend } from '../../../services/Observation service/ObservationService.js';
// RQ_HSE_4_4_25_18_22
import { getDevInterface } from '../../../events/buttonEvents.js';
// RQ_HSE_4_4_25_18_22
import { carEntryDesktopSave } from '../../../utils/carEntrySaveDesktopParity.js';
// RQ_HSE_12_4_26_00_40 — C++ DisplayFieldChange year/serial; block DELETE when ATGNR=Y
import { applyCrentryDateYearSerialIfChanged } from '../../../utils/carCrentryFieldChangeParity.js';
import { shouldBlockDeleteAutoGeneratedCar } from '../../../utils/carTransitionGuard.js';

/* RQ_HSE_12_4_26_00_40 — removed TAB_NEW_SERIAL_CONFIG for HSE_CRCTVEACCENT* tabs on this screen:
   HSE_TGCRENTRY uses HSE_CRENTRY / Actions Entry tabs elsewhere; CRCTVEACCENT serials belong on Creative_Access_Entry (HSE_TGCRCTVEACCENT). */

function escSql(v) {
  return String(v ?? '').replace(/'/g, "''");
}

async function getOwnerDepartment(devInterfaceObj) {
  const exec = devInterfaceObj?.executeSQLPromise || devInterfaceObj?.executeSQL;
  if (typeof exec !== 'function') return '';
  try {
    const rs = await exec(`SELECT TOP 1 ISNULL(HSEPLC_OWNRDPRT,'') AS OWNERDPT FROM HSE_HSEPLC`);
    const row = rs?.recordset?.[0] ?? rs?.[0]?.recordset?.[0] ?? rs?.[0];
    return String(row?.OWNERDPT ?? row?.ownerdpt ?? '').trim();
  } catch (e) {
    console.warn('[Web_HSE] CAR Entry owner department lookup:', e);
    return '';
  }
}

async function getUserDepartment(devInterfaceObj, userObj) {
  const exec = devInterfaceObj?.executeSQLPromise || devInterfaceObj?.executeSQL;
  if (typeof exec !== 'function') return '';
  const login =
    (typeof devInterfaceObj?.getUserName === 'function' ? devInterfaceObj.getUserName() : '') ||
    userObj?.LogIn ||
    userObj?.LOGIN ||
    '';
  const userLogin = String(login).trim();
  if (!userLogin) return '';

  try {
    const sql = `SELECT TOP 1 ISNULL(EMPLOYEE_WSHOP,'') AS EMPDEP FROM CMN_EMPLOYEE WHERE EMPLOYEE_USRID = '${escSql(userLogin)}' OR EMPLOYEE_LOGINNAME = '${escSql(userLogin)}'`;
    const rs = await exec(sql);
    const row = rs?.recordset?.[0] ?? rs?.[0]?.recordset?.[0] ?? rs?.[0];
    return String(row?.EMPDEP ?? row?.empdep ?? '').trim();
  } catch (e) {
    console.warn('[Web_HSE] CAR Entry user department lookup:', e);
    return '';
  }
}

function cleanScalar(v) {
  if (v == null) return '';
  const s = String(v).trim();
  if (s === 'undefined' || s === 'null' || s === 'NaN') return '';
  return s;
}

/** Keep `eventObj.fullRecord` aligned with FormSetField (React state can lag behind save payload). RQ_HSE_4_4_25_18_22 */
function mergeIntoFullRecord(eventObj, fieldLogical, value) {
  const row = eventObj?.fullRecord;
  if (!row || typeof row !== 'object' || value == null || cleanScalar(value) === '') return;
  const u = fieldLogical.toUpperCase();
  const k = Object.keys(row).find((key) => key.toUpperCase() === u) || u;
  row[k] = value;
}

/**
 * C++ NewCarEntryCategory::DisplayToolBarButtonClicked NEW + iComplete==1 for HSE_TGCRENTRY:
 * default site from policy, user department on HSE_CRENTRY (RQ-SF-9-1-23_2_4, RQ_SF_15_3_23_1).
 * RQ_HSE_4_4_25_18_22
 */
async function applyNewCarEntryMainDefaults(devInterfaceObj, eventObj) {
  const { executeSQLPromise, FormSetField } = devInterfaceObj || {};
  if (typeof FormSetField !== 'function' || typeof executeSQLPromise !== 'function') return;

  try {
    const siteData = await executeSQLPromise(`EXECUTE GetPolicyValue 'HSE_HSEPLC','HSEPLC_DFLST'`);
    const r0 = siteData?.recordset?.[0];
    const site = r0 ? cleanScalar(Object.values(r0)[0]) : '';
    if (site) {
      FormSetField('HSE_CRENTRY', 'CRENTRY_ST', site, 'scr');
      try {
        FormSetField('HSE_TgCrEntry', 'CRENTRY_ST', site, 'scr');
      } catch (_) {
        /* ignore */
      }
      mergeIntoFullRecord(eventObj, 'CRENTRY_ST', site);
    }
  } catch (e) {
    console.warn('[Web_HSE] CAR Entry NEW default site (desktop parity):', e);
  }

  const userDept = await getUserDepartment(devInterfaceObj, eventObj || {});
  if (userDept) {
    FormSetField('HSE_CRENTRY', 'CRENTRY_DPR', userDept, 'scr');
    try {
      FormSetField('HSE_TgCrEntry', 'CRENTRY_DPR', userDept, 'scr');
    } catch (_) {
      /* ignore */
    }
    mergeIntoFullRecord(eventObj, 'CRENTRY_DPR', userDept);
  }
}

export async function ButtonClicked(eventObj) {
  const { Button_Name, strScrTag, devInterfaceObj } = eventObj || {};
  const handled = await handleCarButton(Button_Name, strScrTag, eventObj, devInterfaceObj);
  if (!handled) sendButtonClickToBackend((Button_Name || '').toUpperCase(), strScrTag, eventObj, devInterfaceObj);
}

// RQ_HSE_4_4_25_18_22 — toolbar: NEW defaults, SAVE desktop parity (pre/post)
export async function toolBarButtonClicked(eventObj, callBackFn) {
  const devInterface = eventObj.devInterfaceObj || getDevInterface() || {};
  const strTabTag = (eventObj.strTabTag && eventObj.strTabTag.toString().toUpperCase()) || '';
  const strBtnName = (eventObj.strBtnName && eventObj.strBtnName.toString().toUpperCase()) || '';
  const complete = eventObj.complete;
  const completeStr = complete == null ? '' : String(complete).trim();
  const isCarSavePostPhase = complete === 1 || completeStr === '1';
  /** Pre phase: falsy 0/''/false/undefined or explicit '0' (string '0' is truthy to `!complete`). */
  const isCarSavePrePhase =
    !isCarSavePostPhase &&
    (complete == null ||
      complete === '' ||
      complete === 0 ||
      complete === false ||
      completeStr === '0');
  const scrUpper = String(eventObj.strScrTag || '').toUpperCase();

  try {
    if (strBtnName === 'NEW' && isCarSavePostPhase && !strTabTag && scrUpper === 'HSE_TGCRENTRY') {
      await applyNewCarEntryMainDefaults(devInterface, eventObj);
    }
  } catch (e) {
    console.warn('[Web_HSE] CAR Entry NEW main defaults:', e);
  }

  try {
    if (strBtnName === 'SAVE' && scrUpper === 'HSE_TGCRENTRY' && !strTabTag) {
      if (isCarSavePrePhase) {
        await carEntryDesktopSave.preSave(devInterface, eventObj);
      } else if (isCarSavePostPhase) {
        await carEntryDesktopSave.postSave(devInterface, eventObj);
      }
    }
  } catch (e) {
    console.warn('[Web_HSE] CAR Entry SAVE desktop parity:', e);
  }

  // RQ_HSE_12_4_26_00_40 — C++: block DELETE when CRENTRY_ATGNR = Y (toolbar may use pre/post phases)
  if (strBtnName === 'DELETE' && !strTabTag && scrUpper === 'HSE_TGCRENTRY') {
    const blocked = await shouldBlockDeleteAutoGeneratedCar(devInterface, eventObj);
    if (blocked) return;
  }

  if (typeof callBackFn === 'function') callBackFn(eventObj);
}

/**
 * C++ NewCarEntryCategory::DisplayFieldChange — CRENTRY_CRDT year vs CRENTRY_CRYR.
 * RQ_HSE_12_4_26_00_40
 */
export async function SubFieldChanged(strScrTag, strTabTag, fieldName, oldFieldVal, fieldVal, devInterfaceObj) {
  const scr = String(strScrTag || '').toUpperCase();
  const fld = String(fieldName || '').toUpperCase();
  const tab = String(strTabTag || '').trim();
  if (scr === 'HSE_TGCRENTRY' && !tab && fld === 'CRENTRY_CRDT') {
    try {
      await applyCrentryDateYearSerialIfChanged(devInterfaceObj);
    } catch (e) {
      console.warn('[Web_HSE] RQ_HSE_12_4_26_00_40 CAR Entry SubFieldChanged CRENTRY_CRDT:', e);
    }
  }
  return { cancel: 0 };
}

export async function ShowScreen(setScreenDisableBtn, strScrTag, strTabTag, devInterfaceObj) {
  setScreenDisableBtn(false, false, false);
}

/**
 * Desktop parity (HSEMSCommonCategory ID_NEWCARMODULE_CARENTRY):
 * If user department != owner department, apply WHERE CRENTRY_DPR='<userDept>' on CAR Entry list.
 */
export async function onMenuItemClicked(userObj, strScrTag, callBackFn) {
  const tag = String(strScrTag || '').toUpperCase().trim();
  if (tag !== 'HSE_TGCRENTRY') {
    callBackFn({ isAllowed: true, strScrCriteria: '', strMsg: '' });
    return;
  }

  const dev = getDevInterface() || {};
  const ownerDept = await getOwnerDepartment(dev);
  const userDept = await getUserDepartment(dev, userObj);

  let strScrCriteria = '';
  if (userDept && ownerDept && userDept !== ownerDept) {
    strScrCriteria = `WHERE CRENTRY_DPR='${escSql(userDept)}'`;
  }

  callBackFn({ isAllowed: true, strScrCriteria, strMsg: '' });
}
