// arFlwupVstCategory.cpp: implementation of the CarFlwupVstCategory class.
//
//////////////////////////////////////////////////////////////////////

#include "stdafx.h"
#include "CARFlwupVstCategory.h"

//////////////////////////////////////////////////////////////////////
// Construction/Destruction
//////////////////////////////////////////////////////////////////////
CarFlwupVstCategory::CarFlwupVstCategory(CCategory *pCategory):CarCategory(pCategory)
{
	m_pCategory    = pCategory;
	m_FSATableName = "HSE_TGCARFLWUPVSTS";
	m_strScreen	   = "Corrective Action Approval";
}

CarFlwupVstCategory::~CarFlwupVstCategory(){}

HRESULT CarFlwupVstCategory::OpenScreen(CString strCaption,CString strSQL,long lMenuID,long lParam,BOOL bModal,BOOL bFilterMode)
{		
	bool IsCARFlwUpReqrd=CheckPolicy(Is_CAR_Follow_Up_Required);
	if(IsCARFlwUpReqrd==true)
	{
		return CarCategory::OpenScreen(strCaption,strSQL,lMenuID,lParam,bModal,bFilterMode);		
	} else {
		ShowMessageEx(IDS_CARFR,"",IV_NOICON,"Policy change required");
		return S_FALSE;
	}
}

HRESULT CarFlwupVstCategory::DisplayCustomButtonClicked(CUSTOMBUTTONCLICKED* pCustomButtonClicked)
{
	CString strBtnName(pCustomButtonClicked->Button_Name);
	if(strBtnName=="CLS2NDCYCL")
	{
		bool bCARClosed = false;
		bCARClosed = CloseCarWithFLwUp(pCustomButtonClicked);
		if(bCARClosed) {
			CString strCARSerial = FormGetField("HSE_CRCTVEACCENT","CRCTVEACCENT_NO");
			CString strDep		 = FormGetField("HSE_CRCTVEACCENT","CRCTVEACCENT_DPRT");
			CString strDepMail   = getDepMail(strDep);
			closeCARNotification(strDepMail,strCARSerial); 
			RefreshScreen("",REFRESH_SELECTED);
		}
	}
	else if (strBtnName=="CRCTVEACCENT_CARFLWUPVSTS_CNCL") {
		if(OpenReasonsScr("Cancel Reasons","3",true)){			
			CancelCorrectiveAction(pCustomButtonClicked);			
		}
	}
	else if (strBtnName=="CRCTVEACCENT_CARFLWUPVSTS_RJC") {
		CString strAutoGenerated = FormGetField("HSE_CRCTVEACCENT","CRCTVEACCENT_AUTOGNRTD");
		strAutoGenerated.MakeUpper();
		if(strAutoGenerated == "N") {
			if(OpenReasonsScr("Reject Reasons","3",true)){
				RejectCorrectiveAction(pCustomButtonClicked);
			}
		}
		else {
			AfxMessageBox("Automatic generated CARs can be cancelled only.");
		}
	}
	return CarCategory::DisplayCustomButtonClicked(pCustomButtonClicked);
}


HRESULT CarFlwupVstCategory::DisplayTabSelected(tag_TabSelected *pTabSelected)
{
	return CarCategory::DisplayTabSelected (pTabSelected);
}

HRESULT CarFlwupVstCategory::DisplayScreenReady(SCREENREADY *pScreenReady)
{
	EnableToolbar("",TOOLBAR_NEW,FALSE);
	//HSEMS New requirements_27_10_2020  , 5 - Disable delete button
	EnableToolbar("",TOOLBAR_DELETE,FALSE);
	return CarCategory::DisplayScreenReady(pScreenReady);
}

bool CarFlwupVstCategory::CloseCarWithFLwUp(CUSTOMBUTTONCLICKED* pCustomButtonClicked)
{
	/*deleted code please check source safe*/	
	bool bCARClosed = false;
	CString strSQL;
	CString strUserName = GetUserLogin();
	CString strSourceScreenName = GetScrCptnByTag(66,pCustomButtonClicked->Form_Tag,"");
	CString KeyFieldValue = GetKeyField(pCustomButtonClicked->Form_Tag,pCustomButtonClicked->pMultiSelectedRows);
	strSQL.Format("EXECUTE closeCARTXN '%s','%s','%s'",KeyFieldValue,strSourceScreenName,strUserName);
	long lRetVal = ExecuteSQL(strSQL);	
	if(lRetVal !=0) 
		bCARClosed = true;
	return bCARClosed;
}

long CarFlwupVstCategory::ShowCorrectiveActionFollowupvisit(CString strCriteria)
{
	m_nCurrentCard=ID_HSE_CRCTVACTNFLWUPVSTS;
	return ParentManage("HSE_TGCARFLWUPVSTS",TRUE,TRUE,TRUE,"HSE_CRCTVEACCENT",strCriteria);
}