/**
 * Shared custom button handlers for all CAR / Action Tracking screens.
 * C++: NewCarEntryCategory::DisplayCustomButtonClicked and related.
 * Screens: HSE_TGCRENTRY, HSE_TGCRRVW, HSE_TGCRAPRVL, HSE_TGACTNSENTRY, HSE_TGACTNSRVIW, HSE_TGCRFLOUP, HSE_TGCREDTNG
 */

import { getCurrentRecordPRMKY, openRejectReasonScreen } from './rejectReasonUtils.js';

const CAR_REVIEW_INFO_TAG = 'HSE_CrRvwInf';
const CAR_APPROVE_INFO_TAG = 'HSE_CrApprvlInf';
const REJECT_REASON_TAG = 'HSE_TGRJCTRSN';
const OBSERVATION_INQUIRY_TAG = 'HSE_TgNrstMiscInq';
const AUDIT_PLAN_INQUIRY_TAG = 'HSE_TgAdtPlnInq';

const CORRECTIVE_ACTIONS_BY_SCREEN = {
  'HSE_TGCRAPRVL': 'HSE_TGCRRCTVACTNS',
  'HSE_TGCREDTNG': 'HSE_TGCRRCTVACTNS',
  'HSE_TGACTNSRVIW': 'HSE_TgCrrctvActns_Rvw',
  'HSE_TGCRFLOUP': 'HSE_TgCrrctvActnsFlwUp',
  'HSE_TGACTNSENTRY': 'HSE_TgCrrctvActns_ActEnt'
};

const REJECT_SOURCE_BY_SCREEN = {
  'HSE_TGCRRVW': 'CRCTVEACCENT-RV',
  'HSE_TGCRAPRVL': 'CRCTVEACCENT-AP',
  'HSE_TGACTNSENTRY': 'CRCTVEACCENT-AE',
  'HSE_TGACTNSRVIW': 'ACTION-RV',
  'HSE_TGCRFLOUP': 'CARFLOWUP-RV'
};

const CRRCTVACTNS_LNKWTHMN = 'CRRCTVACTNS_LNKWTHMN';
const CrRvwInf_LnkWthMn = 'CrRvwInf_LnkWthMn';
const CrRvwInf_MdlTyp = 'CrRvwInf_MdlTyp';
const CrApprvlInf_LnkWthMn = 'CrApprvlInf_LnkWthMn';
const CrApprvlInf_MdlTyp = 'CrApprvlInf_MdlTyp';
const SOURCE_APPROVE = 'CRCTVEACCENT-AP';

function escapeSqlString(val) {
  if (val == null) return '';
  return String(val).replace(/'/g, "''");
}

function getFieldFromRecord(eventObj, fieldName) {
  const fullRecordArr = eventObj?.fullRecord ?? eventObj?.fullRecordArr ?? [];
  const rec = Array.isArray(fullRecordArr) ? fullRecordArr[0] : fullRecordArr;
  if (!rec || typeof rec !== 'object') return '';
  const u = String(fieldName).toUpperCase();
  for (const k of Object.keys(rec)) {
    if (k.toUpperCase() === u) return (rec[k] != null ? String(rec[k]) : '').trim();
  }
  return '';
}

function openCarReviewInfo(openScr, strPrimKey, strSourceModule = '') {
  const esc = escapeSqlString(strPrimKey);
  const criteria = strSourceModule
    ? `SELECT * FROM ${CAR_REVIEW_INFO_TAG} WHERE (${CrRvwInf_LnkWthMn}= '${esc}') AND (${CrRvwInf_MdlTyp}= '${escapeSqlString(strSourceModule)}')`
    : `SELECT * FROM ${CAR_REVIEW_INFO_TAG} WHERE (${CrRvwInf_LnkWthMn}= '${esc}')`;
  const defValObj = { [CrRvwInf_LnkWthMn]: strPrimKey, [CrRvwInf_MdlTyp]: strSourceModule };
  openScr(CAR_REVIEW_INFO_TAG, {}, criteria, 'edit', false, defValObj, false, true);
}

function openCarApproveInfo(openScr, strPrimKey) {
  const esc = escapeSqlString(strPrimKey);
  const criteria = `SELECT * FROM ${CAR_APPROVE_INFO_TAG} WHERE (${CrApprvlInf_LnkWthMn}= '${esc}') AND (${CrApprvlInf_MdlTyp}= '${SOURCE_APPROVE}')`;
  const defValObj = { [CrApprvlInf_LnkWthMn]: strPrimKey, [CrApprvlInf_MdlTyp]: SOURCE_APPROVE };
  openScr(CAR_APPROVE_INFO_TAG, {}, criteria, 'edit', false, defValObj, false, true);
}

function openCorrectiveActionsPopup(openScr, strScrTag, strKeyField) {
  const popupTag = CORRECTIVE_ACTIONS_BY_SCREEN[strScrTag];
  if (!popupTag || !strKeyField) return;
  const esc = escapeSqlString(strKeyField);
  const criteria = `SELECT * FROM HSE_CRRCTVACTNS WHERE (${CRRCTVACTNS_LNKWTHMN}= '${esc}')`;
  const defValObj = { [CRRCTVACTNS_LNKWTHMN]: strKeyField };
  openScr(popupTag, {}, criteria, 'edit', false, defValObj, false, false);
}

function handleViewSourceTxn(eventObj, devInterfaceObj) {
  const openScr = devInterfaceObj?.openScr;
  if (typeof openScr !== 'function') return;
  const strAutoGenerated = (getFieldFromRecord(eventObj, 'CRENTRY_ATGNR') || '').toUpperCase();
  if (strAutoGenerated !== 'Y') {
    const msg = devInterfaceObj.getCurrentLang?.() === 'ar' ? 'القيمة التلقائية ليست نعم' : "Auto generated is set to 'No'";
    if (devInterfaceObj.AskYesNoMessage) devInterfaceObj.AskYesNoMessage(msg);
    return;
  }
  const strCARSrc = (getFieldFromRecord(eventObj, 'CRENTRY_CRSRC') || '').toUpperCase().replace(/\s+/g, ' ').trim();
  const txnYr = getFieldFromRecord(eventObj, 'CRENTRY_TXNYR');
  const txnNo = getFieldFromRecord(eventObj, 'CRENTRY_TXNN');
  if (strCARSrc === 'OBSERVATION' || strCARSrc === 'NEAR MISS') {
    const strCriteria = `(NrstMiscEnt_Yr = '${escapeSqlString(txnYr)}') AND (NrstMiscEnt_NrstMiscNum = '${escapeSqlString(txnNo)}')`;
    openScr(OBSERVATION_INQUIRY_TAG, {}, strCriteria, 'list', false, {}, false, false);
  } else if (strCARSrc === 'INTERNAL AUDIT') {
    const strCriteria = `(ADTPLNENT_ADTYR = '${escapeSqlString(txnYr)}') AND (ADTPLNENT_ADTNUM = '${escapeSqlString(txnNo)}')`;
    openScr(AUDIT_PLAN_INQUIRY_TAG, {}, strCriteria, 'list', false, {}, false, false);
  } else {
    const msg = devInterfaceObj.getCurrentLang?.() === 'ar' ? 'مصدر CAR غير مدعوم' : 'CAR source not supported for View Source TXN';
    if (devInterfaceObj.AskYesNoMessage) devInterfaceObj.AskYesNoMessage(msg);
  }
}

/** View Reject Reason (locked) for CAR Entry - open with criteria CRCTVEACCENT% */
function handleViewRejectReasons(eventObj, devInterfaceObj) {
  const openScr = devInterfaceObj?.openScr;
  if (typeof openScr !== 'function') return;
  const strPrimKey = getCurrentRecordPRMKY(eventObj);
  if (!strPrimKey) return;
  const esc = escapeSqlString(strPrimKey);
  const strCriteria = `SELECT * FROM HSE_RJCTRSN WHERE (RJCTRSN_LINKWITHMAIN= '${esc}') AND (RJCTRSN_MODULETYPE like 'CRCTVEACCENT%')`;
  openScr(REJECT_REASON_TAG, {}, strCriteria, 'edit', false, {}, false, true);
}

/** ENTRY_COMPLETED for CAR Entry (HSE_TGCRENTRY) - insert tracing, set status 05, save */
async function handleEntryCompletedCarEntry(eventObj, devInterfaceObj) {
  const { executeSQLPromise, FormSetField, doToolbarAction, refreshData, getUserName } = devInterfaceObj || {};
  if (!executeSQLPromise || !FormSetField) return;
  const strPrmKy = getCurrentRecordPRMKY(eventObj);
  if (!strPrmKy) return;
  const strUserName = (typeof getUserName === 'function' ? getUserName() : '') || '';
  try {
    await executeSQLPromise(`insert into HSE_CRENTRY_TRC(CRENTRY_TRC_LNK,CRENTRY_TRC_DATTIM,CRENTRY_TRC_ACCDESC,SRCSCRN,CrEntry_Trc_EntUsr) values(${strPrmKy},GETDATE(),'Entry Completed','CAR Entry','${escapeSqlString(strUserName)}')`);
    FormSetField('HSE_TgCrEntry', 'CRENTRY_CRSTT', '05', 'scr');
    if (typeof doToolbarAction === 'function') doToolbarAction('SAVE', 'HSE_TgCrEntry', '');
    if (typeof refreshData === 'function') refreshData('');
  } catch (e) {
    console.warn('[Web_HSE] CAR Entry ENTRY_COMPLETED:', e);
    if (devInterfaceObj.AskYesNoMessage) devInterfaceObj.AskYesNoMessage('Error applying Entry Completed');
  }
}

/** ENTRY_COMPLETED for Actions Entry - validations + tracing + status 16 + updates + save */
async function handleEntryCompletedActionsEntry(eventObj, devInterfaceObj) {
  const { executeSQLPromise, FormSetField, doToolbarAction, refreshData, getUserName, getValFromRecordSet } = devInterfaceObj || {};
  if (!executeSQLPromise || !FormSetField || !doToolbarAction || !refreshData) return;
  const strPrmKy = getCurrentRecordPRMKY(eventObj);
  if (!strPrmKy) return;
  const getCount = async (sql) => {
    const r = await executeSQLPromise(sql);
    const row = r?.recordset?.[0] ?? r?.[0];
    const c = row && (getValFromRecordSet ? getValFromRecordSet(r, 'C') : (row.C ?? row.c));
    return parseInt(c, 10) || 0;
  };
  try {
    if ((await getCount(`SELECT COUNT(*) AS C FROM HSE_ACTNSENTRY_RtCss WHERE prmky=${strPrmKy}`)) === 0) {
      if (devInterfaceObj.AskYesNoMessage) devInterfaceObj.AskYesNoMessage('Must enter root causes');
      return;
    }
    if ((await getCount(`SELECT COUNT(*) AS C FROM HSE_ACTNSENTRY_RtCss WHERE AutoFieldNum NOT IN (SELECT isnull(CrrctvActns_Lnkwthmn,0) FROM HSE_CrrctvActns) AND prmky=${strPrmKy}`)) !== 0) {
      if (devInterfaceObj.AskYesNoMessage) devInterfaceObj.AskYesNoMessage('Each root cause must at least have 1 action');
      return;
    }
    if ((await getCount(`SELECT COUNT(*) AS C FROM HSE_ACTNSENTRY_CRR WHERE prmky=${strPrmKy}`)) === 0) {
      if (devInterfaceObj.AskYesNoMessage) devInterfaceObj.AskYesNoMessage('User MUST enter at least (1) record in Corrections tab');
      return;
    }
  } catch (e) {
    console.warn('[Web_HSE] ENTRY_COMPLETED validation:', e);
    if (devInterfaceObj.AskYesNoMessage) devInterfaceObj.AskYesNoMessage('Validation error');
    return;
  }
  const strUserName = (typeof getUserName === 'function' ? getUserName() : '') || '';
  try {
    await executeSQLPromise(`insert into HSE_CRENTRY_TRC(CRENTRY_TRC_LNK,CRENTRY_TRC_DATTIM,CRENTRY_TRC_ACCDESC,SRCSCRN,CrEntry_Trc_EntUsr) values(${strPrmKy},GETDATE(),'Entry Completed','Actions Entry','${escapeSqlString(strUserName)}')`);
    FormSetField('HSE_TgActnsEntry', 'CRENTRY_CRSTT', '16', 'scr');
    await executeSQLPromise(`update HSE_ACTNSENTRY_CRR set CRRCTVACTNS_LnkCss_Acc='Y',ACTNSENTRY_Crr_ActStt='A' where PrmKy=${strPrmKy}`);
    await executeSQLPromise(`update HSE_CRRCTVACTNS set CRRCTVACTNS_Acc='Y', CRRCTVACTNS_ACTSTT=3 where CrrctvActns_LnkWthMn in (select AutoFieldNum from HSE_ACTNSENTRY_RTCSS where PrmKy=${strPrmKy})`);
    if (typeof doToolbarAction === 'function') doToolbarAction('SAVE', 'HSE_TgActnsEntry', '');
    if (typeof refreshData === 'function') refreshData('');
  } catch (e) {
    console.warn('[Web_HSE] ENTRY_COMPLETED apply:', e);
    if (devInterfaceObj.AskYesNoMessage) devInterfaceObj.AskYesNoMessage('Error applying Entry Completed');
  }
}

/** CLOSE_CAR: validate then set CRENTRY_CRSTT=25, save, refresh. formTag = current screen tag. */
async function handleCloseCar(eventObj, devInterfaceObj, formTag) {
  const { executeSQLPromise, FormSetField, doToolbarAction, refreshData } = devInterfaceObj || {};
  if (!executeSQLPromise || !FormSetField) return;
  const strPrmKy = getCurrentRecordPRMKY(eventObj);
  if (!strPrmKy) return;
  const getCount = async (sql) => {
    try {
      const r = await executeSQLPromise(sql);
      return r?.recordsAffected ?? r?.rowsAffected ?? 0;
    } catch (_) { return -1; }
  };
  const unacceptedCorr = await getCount(`update HSE_ACTNSENTRY_CRR set prmky=prmky where prmky=${strPrmKy} AND isnull(ACTNSENTRY_CRR_ACTACC,'') <> 'Y'`);
  if (unacceptedCorr > 0) {
    if (devInterfaceObj.AskYesNoMessage) devInterfaceObj.AskYesNoMessage('Some "actions" are not accepted, please check the Corrections TAB');
    return;
  }
  const unacceptedAct = await getCount(`update HSE_CRRCTVACTNS set CrrctvActns_LnkWthMn=CrrctvActns_LnkWthMn where CrrctvActns_LnkWthMn in (select AutoFieldNum from HSE_ACTNSENTRY_RTCSS where PrmKy=${strPrmKy}) and isnull(CRRCTVACTNS_ACTACC,'') <> 'y'`);
  if (unacceptedAct > 0) {
    if (devInterfaceObj.AskYesNoMessage) devInterfaceObj.AskYesNoMessage('Some "actions" are not accepted, please check the Corrective Actions');
    return;
  }
  const closeDate = getFieldFromRecord(eventObj, 'CRENTRY_CRCLSDT');
  if (!closeDate) {
    if (devInterfaceObj.AskYesNoMessage) devInterfaceObj.AskYesNoMessage('Please enter CAR closed date');
    return;
  }
  const tag = formTag || 'HSE_TgActnsRviw';
  try {
    FormSetField(tag, 'CRENTRY_CRSTT', '25', 'scr');
    if (typeof doToolbarAction === 'function') doToolbarAction('SAVE', tag, '');
    if (typeof refreshData === 'function') refreshData('');
  } catch (e) {
    console.warn('[Web_HSE] CLOSE_CAR:', e);
  }
}

/**
 * Main entry: handle CAR custom button. Returns true if the button was handled for this screen.
 * @param {string} buttonName - e.g. VIEW_CAR_REVIEW_INFO
 * @param {string} strScrTag - e.g. HSE_TGACTNSENTRY (uppercase)
 * @param {Object} eventObj - ButtonClicked event
 * @param {Object} devInterfaceObj - dev interface
 * @returns {Promise<boolean>}
 */
export async function handleCarButton(buttonName, strScrTag, eventObj, devInterfaceObj) {
  const btn = (buttonName && String(buttonName).toUpperCase()) || '';
  const scr = (strScrTag && String(strScrTag).toUpperCase()) || '';

  const openScr = devInterfaceObj?.openScr;
  const strPrimKey = getCurrentRecordPRMKY(eventObj);
  const strKeyField = getFieldFromRecord(eventObj, 'AutoFieldNum') || getFieldFromRecord(eventObj, 'AUTOFIELDNUM');

  if (btn === 'VIEW_SOURCE_TXN') {
    if (['HSE_TGCRENTRY', 'HSE_TGCRRVW', 'HSE_TGACTNSENTRY', 'HSE_TGACTNSRVIW', 'HSE_TGCRAPRVL'].includes(scr)) {
      handleViewSourceTxn(eventObj, devInterfaceObj);
      return true;
    }
  }

  if (btn === 'CRENTRY_VWRJCTRSNS' && scr === 'HSE_TGCRENTRY') {
    handleViewRejectReasons(eventObj, devInterfaceObj);
    return true;
  }

  if (btn === 'ENTRY_COMPLETED') {
    if (scr === 'HSE_TGCRENTRY') {
      await handleEntryCompletedCarEntry(eventObj, devInterfaceObj);
      return true;
    }
    if (scr === 'HSE_TGACTNSENTRY') {
      await handleEntryCompletedActionsEntry(eventObj, devInterfaceObj);
      return true;
    }
  }

  if (btn === 'REJECT_CAR') {
    const src = REJECT_SOURCE_BY_SCREEN[scr];
    if (src && typeof openScr === 'function' && strPrimKey) {
      openRejectReasonScreen(openScr, src, strPrimKey);
      return true;
    }
  }

  if (btn === 'VIEW_CAR_REVIEW_INFO') {
    if (['HSE_TGCRAPRVL', 'HSE_TGACTNSENTRY', 'HSE_TGCREDTNG'].includes(scr) && openScr && strPrimKey) {
      openCarReviewInfo(openScr, strPrimKey, '');
      return true;
    }
  }

  if (btn === 'VIEW_CAR_APPROVE_INFO') {
    if (['HSE_TGACTNSENTRY', 'HSE_TGCREDTNG'].includes(scr) && openScr && strPrimKey) {
      openCarApproveInfo(openScr, strPrimKey);
      return true;
    }
  }

  if (btn === 'CORRECTIVE_ACTIONS') {
    if (CORRECTIVE_ACTIONS_BY_SCREEN[scr] && openScr && strKeyField) {
      openCorrectiveActionsPopup(openScr, scr, strKeyField);
      return true;
    }
  }

  if (btn === 'CAR_REVIEW_INFO' && scr === 'HSE_TGCRRVW') {
    if (openScr && strPrimKey) {
      openCarReviewInfo(openScr, strPrimKey, 'CRCTVEACCENT-RV');
      return true;
    }
  }

  if (btn === 'CAR_APPROVAL_INFO' && scr === 'HSE_TGCRAPRVL') {
    if (openScr && strPrimKey) {
      openCarApproveInfo(openScr, strPrimKey);
      return true;
    }
  }

  if (btn === 'CANCEL_CAR' && scr === 'HSE_TGCRAPRVL') {
    if (openScr && strPrimKey) {
      openRejectReasonScreen(openScr, 'CRCTVEACCENT-AP', strPrimKey);
      return true;
    }
  }

  if (btn === 'CLOSE_CAR') {
    if (['HSE_TGACTNSRVIW', 'HSE_TGCRFLOUP'].includes(scr)) {
      await handleCloseCar(eventObj, devInterfaceObj, eventObj?.strScrTag || strScrTag);
      return true;
    }
  }

  if (btn === 'ACCEPT_CAR') {
    if (scr === 'HSE_TGCRRVW' && openScr && strPrimKey) {
      openCarReviewInfo(openScr, strPrimKey, 'CRCTVEACCENT-RV');
      return true;
    }
    if (scr === 'HSE_TGACTNSRVIW') {
      const { executeSQLPromise, FormSetField, doToolbarAction, refreshData } = devInterfaceObj || {};
      if (strPrimKey && executeSQLPromise && FormSetField) {
        try {
          const r1 = await executeSQLPromise(`update HSE_ACTNSENTRY_CRR set prmky=prmky where prmky=${strPrimKey} AND isnull(CRRCTVACTNS_LNKCSS_ACC,'') <> 'Y'`);
          if ((r1?.recordsAffected ?? r1?.rowsAffected ?? 0) > 0) {
            if (devInterfaceObj.AskYesNoMessage) devInterfaceObj.AskYesNoMessage('Please check the corrections TAB');
            return true;
          }
          const r2 = await executeSQLPromise(`update HSE_CRRCTVACTNS set CRRCTVACTNS_lnkwthmn=CRRCTVACTNS_lnkwthmn where CRRCTVACTNS_acc='N' and CRRCTVACTNS_lnkwthmn in (select autoFieldnum from HSE_ACTNSENTRY_RTCSS where prmky=${strPrimKey})`);
          if ((r2?.recordsAffected ?? r2?.rowsAffected ?? 0) > 0) {
            if (devInterfaceObj.AskYesNoMessage) devInterfaceObj.AskYesNoMessage('Please check the Root Causes TAB & related corrective actions');
            return true;
          }
          const { getUserName } = devInterfaceObj;
          const un = (typeof getUserName === 'function' ? getUserName() : '') || '';
          await executeSQLPromise(`insert into HSE_CRENTRY_TRC(CRENTRY_TRC_LNK,CRENTRY_TRC_DATTIM,CRENTRY_TRC_ACCDESC,SRCSCRN,CrEntry_Trc_EntUsr) values(${strPrimKey},GETDATE(),'CAR Accepted','Actions Review','${escapeSqlString(un)}')`);
          FormSetField('HSE_TgActnsRviw', 'CRENTRY_CRSTT', '19', 'scr');
          const upd = `with ROOT_CAUSES_TRGTDT as (select max(CRRCTVACTNS_trgDt) RootCauseTrgtdt from HSE_CRRCTVACTNS where CRRCTVACTNS_lnkWthMn in (select Autofieldnum from HSE_ACTNSENTRY_RTCSS where prmky=${strPrimKey})), MAIN_TRGTDT as (select CRENTRY_CRTRGDT MainTrgtdt from hse_CRENTRY where prmky=${strPrimKey}), JOIN_THE_TWO as(select * from ROOT_CAUSES_TRGTDT,MAIN_TRGTDT) update JOIN_THE_TWO set MainTrgtdt=RootCauseTrgtdt where isnull(MainTrgtdt,0)<RootCauseTrgtdt`;
          await executeSQLPromise(upd);
          if (typeof doToolbarAction === 'function') doToolbarAction('SAVE', 'HSE_TgActnsRviw', '');
          if (typeof refreshData === 'function') refreshData('');
        } catch (e) {
          console.warn('[Web_HSE] ACCEPT_CAR Actions Review:', e);
        }
      }
      return true;
    }
  }

  if (btn === 'APPROVE_CAR' && scr === 'HSE_TGCRAPRVL') {
    if (openScr && strPrimKey) {
      openCarApproveInfo(openScr, strPrimKey);
      return true;
    }
  }

  return false;
}

export { getCurrentRecordPRMKY, getFieldFromRecord, openRejectReasonScreen };
