/**
 * Client-side guard: CAR workflow actions only from expected CRENTRY_CRSTT (desktop parity).
 * Does not replace DB rules; mitigates accidental out-of-order actions from the web shell.
 * RQ_HSE_12_4_26_00_40
 */

/**
 * @param {Function} executeSQLPromise
 * @param {string} prmky
 * @returns {Promise<string>}
 */
export async function fetchCrentryCrstt(executeSQLPromise, prmky) {
  const pk = String(prmky ?? '').trim();
  if (!pk || !/^\d+$/.test(pk)) return '';
  try {
    const r = await executeSQLPromise(
      `SELECT TOP 1 ISNULL(LTRIM(RTRIM(CRENTRY_CRSTT)),'') AS S FROM HSE_CRENTRY WHERE PrmKy = ${parseInt(pk, 10)}`
    );
    const row = r?.recordset?.[0] ?? r?.[0];
    return String(row?.S ?? row?.s ?? '').trim();
  } catch (e) {
    console.warn('[Web_HSE] RQ_HSE_12_4_26_00_40 fetchCrentryCrstt:', e);
    return '';
  }
}

/**
 * @param {Function} executeSQLPromise
 * @param {string} prmky
 * @param {string[]} allowedFrom — empty = skip check
 * @param {Function} [AskYesNoMessage]
 * @param {string} [message]
 * @returns {Promise<boolean>}
 */
export async function assertCrentryStatusAllows(
  executeSQLPromise,
  prmky,
  allowedFrom,
  AskYesNoMessage,
  message
) {
  if (!allowedFrom || allowedFrom.length === 0) return true;
  const current = await fetchCrentryCrstt(executeSQLPromise, prmky);
  const ok = allowedFrom.some((x) => String(x).trim() === current);
  if (!ok && typeof AskYesNoMessage === 'function') {
    AskYesNoMessage(
      message ||
        'This action is not allowed for the current CAR status. Please refresh and follow the workflow order. (RQ_HSE_12_4_26_00_40)'
    );
  }
  return ok;
}

const TABLE_MAIN_ATGNR = 'HSE_CRENTRY';
const FORM_TAG_ATGNR = 'HSE_TgCrEntry';

/**
 * Block CAR Entry DELETE when CRENTRY_ATGNR = Y (desktop).
 * RQ_HSE_12_4_26_00_40
 * @param {Record<string, unknown>} devInterfaceObj
 * @param {{ fullRecord?: unknown }} [eventObj]
 */
export async function shouldBlockDeleteAutoGeneratedCar(devInterfaceObj, eventObj) {
  const { executeSQLPromise, FormGetField, AskYesNoMessage } = devInterfaceObj || {};
  const readAtgnr = () => {
    if (typeof FormGetField === 'function') {
      let v = FormGetField(TABLE_MAIN_ATGNR, 'CRENTRY_ATGNR', 'SCR');
      if (v == null || String(v).trim() === '') v = FormGetField(FORM_TAG_ATGNR, 'CRENTRY_ATGNR', 'SCR');
      if (v != null && String(v).trim() !== '') return String(v).trim();
    }
    const rec = eventObj?.fullRecord;
    const row = Array.isArray(rec) ? rec[0] : rec;
    if (row && typeof row === 'object') {
      const u = Object.keys(row).find((k) => k.toUpperCase() === 'CRENTRY_ATGNR');
      if (u) return String(row[u] ?? '').trim();
    }
    return '';
  };

  let atgnr = readAtgnr();
  const pk =
    (eventObj?.fullRecord &&
      (Array.isArray(eventObj.fullRecord) ? eventObj.fullRecord[0] : eventObj.fullRecord)?.PRMKY) ??
    (eventObj?.fullRecord &&
      (Array.isArray(eventObj.fullRecord) ? eventObj.fullRecord[0] : eventObj.fullRecord)?.prmky);

  if ((!atgnr || atgnr === '') && typeof executeSQLPromise === 'function' && pk != null && String(pk).trim() !== '') {
    try {
      const pkNum = parseInt(String(pk), 10);
      if (Number.isFinite(pkNum) && pkNum > 0) {
        const r = await executeSQLPromise(
          `SELECT TOP 1 ISNULL(LTRIM(RTRIM(CRENTRY_ATGNR)),'') AS A FROM HSE_CRENTRY WHERE PrmKy = ${pkNum}`
        );
        const row = r?.recordset?.[0] ?? r?.[0];
        atgnr = String(row?.A ?? row?.a ?? '').trim();
      }
    } catch (e) {
      console.warn('[Web_HSE] RQ_HSE_12_4_26_00_40 ATGNR lookup:', e);
    }
  }

  if (atgnr.toUpperCase() === 'Y') {
    if (typeof AskYesNoMessage === 'function') {
      AskYesNoMessage(
        'Cannot delete an auto-generated CAR (CRENTRY_ATGNR = Y). (RQ_HSE_12_4_26_00_40)'
      );
    }
    return true;
  }
  return false;
}
